name: flutter_handle_file
description: Flutter plugin for accepting incoming links - App/Deep Links (Android), Universal Links and Custom URL schemes (iOS).
version: 0.2.0
author: Nicolas Bonamy <nicolas@bonamy.fr>
homepage: https://github.com/nbonamy/flutter_handle_file

dependencies:
  flutter:
    sdk: flutter
  yaml: ^2.1.16

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

flutter:
  plugin:
    androidPackage: fr.bonamy.handlefile
    pluginClass: HandleFilePlugin
